/*
 * Yotarou API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`healthcheck_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum HealthcheckGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`leaderboard_channel_server_id_game_type_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LeaderboardChannelServerIdGameTypeDeleteError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`leaderboard_channel_server_id_game_type_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LeaderboardChannelServerIdGameTypeGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`leaderboard_channel_server_id_game_type_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LeaderboardChannelServerIdGameTypePostError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`leaderboards_game_type_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LeaderboardsGameTypeDeleteError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`leaderboards_server_id_game_type_player_count_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LeaderboardsServerIdGameTypePlayerCountGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`leaderboards_server_id_game_type_top_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LeaderboardsServerIdGameTypeTopGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`leaderboards_server_id_game_type_user_id_increment_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LeaderboardsServerIdGameTypeUserIdIncrementPostError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`leaderboards_server_id_game_type_window_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LeaderboardsServerIdGameTypeWindowGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`server_settings_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ServerSettingsPostError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`server_settings_server_id_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ServerSettingsServerIdDeleteError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`server_settings_server_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ServerSettingsServerIdGetError {
    UnknownValue(serde_json::Value),
}


pub async fn healthcheck_get(configuration: &configuration::Configuration, ) -> Result<String, Error<HealthcheckGetError>> {

    let uri_str = format!("{}/healthcheck", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Ok(content),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<HealthcheckGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn leaderboard_channel_server_id_game_type_delete(configuration: &configuration::Configuration, server_id: &str, game_type: &str) -> Result<String, Error<LeaderboardChannelServerIdGameTypeDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_server_id = server_id;
    let p_game_type = game_type;

    let uri_str = format!("{}/leaderboard-channel/{server_id}/{game_type}", configuration.base_path, server_id=crate::apis::urlencode(p_server_id), game_type=crate::apis::urlencode(p_game_type));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Ok(content),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LeaderboardChannelServerIdGameTypeDeleteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn leaderboard_channel_server_id_game_type_get(configuration: &configuration::Configuration, server_id: &str, game_type: &str) -> Result<models::LeaderboardChannel, Error<LeaderboardChannelServerIdGameTypeGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_server_id = server_id;
    let p_game_type = game_type;

    let uri_str = format!("{}/leaderboard-channel/{server_id}/{game_type}", configuration.base_path, server_id=crate::apis::urlencode(p_server_id), game_type=crate::apis::urlencode(p_game_type));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LeaderboardChannel`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LeaderboardChannel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LeaderboardChannelServerIdGameTypeGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn leaderboard_channel_server_id_game_type_post(configuration: &configuration::Configuration, server_id: &str, game_type: &str) -> Result<models::LeaderboardChannel, Error<LeaderboardChannelServerIdGameTypePostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_server_id = server_id;
    let p_game_type = game_type;

    let uri_str = format!("{}/leaderboard-channel/{server_id}/{game_type}", configuration.base_path, server_id=crate::apis::urlencode(p_server_id), game_type=crate::apis::urlencode(p_game_type));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LeaderboardChannel`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LeaderboardChannel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LeaderboardChannelServerIdGameTypePostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn leaderboards_game_type_delete(configuration: &configuration::Configuration, game_type: &str) -> Result<String, Error<LeaderboardsGameTypeDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_game_type = game_type;

    let uri_str = format!("{}/leaderboards/{game_type}", configuration.base_path, game_type=crate::apis::urlencode(p_game_type));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Ok(content),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LeaderboardsGameTypeDeleteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn leaderboards_server_id_game_type_player_count_get(configuration: &configuration::Configuration, server_id: &str, game_type: &str) -> Result<i64, Error<LeaderboardsServerIdGameTypePlayerCountGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_server_id = server_id;
    let p_game_type = game_type;

    let uri_str = format!("{}/leaderboards/{server_id}/{game_type}/player_count", configuration.base_path, server_id=crate::apis::urlencode(p_server_id), game_type=crate::apis::urlencode(p_game_type));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `i64`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `i64`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LeaderboardsServerIdGameTypePlayerCountGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn leaderboards_server_id_game_type_top_get(configuration: &configuration::Configuration, server_id: &str, game_type: &str) -> Result<Vec<models::UserRanking>, Error<LeaderboardsServerIdGameTypeTopGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_server_id = server_id;
    let p_game_type = game_type;

    let uri_str = format!("{}/leaderboards/{server_id}/{game_type}/top", configuration.base_path, server_id=crate::apis::urlencode(p_server_id), game_type=crate::apis::urlencode(p_game_type));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::UserRanking&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::UserRanking&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LeaderboardsServerIdGameTypeTopGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn leaderboards_server_id_game_type_user_id_increment_post(configuration: &configuration::Configuration, server_id: &str, game_type: &str, user_id: &str) -> Result<models::UserRanking, Error<LeaderboardsServerIdGameTypeUserIdIncrementPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_server_id = server_id;
    let p_game_type = game_type;
    let p_user_id = user_id;

    let uri_str = format!("{}/leaderboards/{server_id}/{game_type}/{user_id}/increment", configuration.base_path, server_id=crate::apis::urlencode(p_server_id), game_type=crate::apis::urlencode(p_game_type), user_id=crate::apis::urlencode(p_user_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UserRanking`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UserRanking`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LeaderboardsServerIdGameTypeUserIdIncrementPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn leaderboards_server_id_game_type_window_get(configuration: &configuration::Configuration, server_id: &str, game_type: &str, user_id: &str) -> Result<Vec<models::UserRanking>, Error<LeaderboardsServerIdGameTypeWindowGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_server_id = server_id;
    let p_game_type = game_type;
    let p_user_id = user_id;

    let uri_str = format!("{}/leaderboards/{server_id}/{game_type}/window", configuration.base_path, server_id=crate::apis::urlencode(p_server_id), game_type=crate::apis::urlencode(p_game_type));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("user_id", &p_user_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::UserRanking&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::UserRanking&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LeaderboardsServerIdGameTypeWindowGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn server_settings_post(configuration: &configuration::Configuration, server_settings: models::ServerSettings) -> Result<models::ServerSettings, Error<ServerSettingsPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_server_settings = server_settings;

    let uri_str = format!("{}/server-settings", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_server_settings);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ServerSettings`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ServerSettings`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ServerSettingsPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn server_settings_server_id_delete(configuration: &configuration::Configuration, server_id: &str) -> Result<String, Error<ServerSettingsServerIdDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_server_id = server_id;

    let uri_str = format!("{}/server-settings/{server_id}", configuration.base_path, server_id=crate::apis::urlencode(p_server_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Ok(content),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ServerSettingsServerIdDeleteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn server_settings_server_id_get(configuration: &configuration::Configuration, server_id: &str) -> Result<models::ServerSettings, Error<ServerSettingsServerIdGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_server_id = server_id;

    let uri_str = format!("{}/server-settings/{server_id}", configuration.base_path, server_id=crate::apis::urlencode(p_server_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ServerSettings`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ServerSettings`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ServerSettingsServerIdGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

