version: "3"
services:
  # Base node image to reuse in ppq-api and discord-bot
  base:
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm install
    volumes:
      - .:/srv:cached

  discordbot-db:
    image: postgres:latest
    ports:
      - ${DISCORD_BOT_DB_HOST}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DISCORD_BOT_DB_NAME}
    volumes:
      - discordbot-db-volume:/var/lib/postgresql/data

  discordbot:
    depends_on:
      - base
      - discordbot-db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DISCORD_BOT_DB_NAME: ${DISCORD_BOT_DB_NAME}
      DISCORD_BOT_DB_HOST: ${DISCORD_BOT_DB_HOST}
      DISCORD_BOT_DB_URL: postgres://postgres:${POSTGRES_PASSWORD}@discordbot-db:5432/${DISCORD_BOT_DB_NAME}
      DISCORD_BOT_API_TOKEN: ${DISCORD_BOT_API_TOKEN}
    volumes_from:
      - base

volumes:
  discordbot-db-volume: #
