version: "3"
services:
  api-db:
    image: postgres:16
    ports:
      - 35432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ppq_api_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - api-db-volume:/var/lib/postgresql/data
  api-cache:
    image: redis:7
    ports:
      - 36379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      api-db:
        condition: service_healthy
  bot-db:
    image: postgres:16
    ports:
      - 35433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ppq_bot_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - bot-db-volume:/var/lib/postgresql/data

volumes:
  api-db-volume: #
  bot-db-volume: #
