version: "3"
services:
  discordbot-db-test:
    image: postgres:latest
    ports:
      - ${DISCORD_BOT_DB_HOST_TEST}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DISCORD_BOT_DB_NAME}
  
  discordbot:
    environment:
      DISCORD_BOT_DB_HOST_TEST: ${DISCORD_BOT_DB_HOST_TEST}
      DISCORD_BOT_DB_URL_TEST: postgres://postgres:${POSTGRES_PASSWORD}@discordbot-db-test:5432/${DISCORD_BOT_DB_NAME}