/*
 * PPQ API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Alias {
    /// Warning: The api will return the alias as an NFKD normalized String!
    #[serde(rename = "alias")]
    pub alias: String,
    #[serde(rename = "char_id")]
    pub char_id: String,
    #[serde(rename = "internal")]
    pub internal: bool,
    #[serde(rename = "card_type")]
    pub card_type: models::CardType,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl Alias {
    pub fn new(alias: String, char_id: String, internal: bool, card_type: models::CardType, updated_at: String) -> Alias {
        Alias {
            alias,
            char_id,
            internal,
            card_type,
            updated_at,
        }
    }
}

