/*
 * PPQ API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BadRequestReason {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "status")]
    pub status: i32,
    #[serde(rename = "detail")]
    pub detail: String,
    #[serde(rename = "invalid_params")]
    pub invalid_params: Vec<String>,
}

impl BadRequestReason {
    pub fn new(title: String, status: i32, detail: String, invalid_params: Vec<String>) -> BadRequestReason {
        BadRequestReason {
            title,
            status,
            detail,
            invalid_params,
        }
    }
}

