/*
 * PPQ API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CardsAndMaterials {
    #[serde(rename = "cards")]
    pub cards: Vec<models::Card>,
    #[serde(rename = "materials")]
    pub materials: Vec<models::Card>,
}

impl CardsAndMaterials {
    pub fn new(cards: Vec<models::Card>, materials: Vec<models::Card>) -> CardsAndMaterials {
        CardsAndMaterials {
            cards,
            materials,
        }
    }
}

