/*
 * PPQ API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Card {
    #[serde(rename = "card_id")]
    pub card_id: String,
    /// Foreign key to the character table
    #[serde(rename = "char_id")]
    pub char_id: String,
    #[serde(rename = "rarity")]
    pub rarity: String,
    /// 6-1, 6-2 (6S)
    #[serde(rename = "rarity_modifier", skip_serializing_if = "Option::is_none")]
    pub rarity_modifier: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    /// NFKD normalized with special characters removed
    #[serde(rename = "name_normalized")]
    pub name_normalized: String,
    #[serde(rename = "jp_name", skip_serializing_if = "Option::is_none")]
    pub jp_name: Option<String>,
    #[serde(rename = "jp_name_normalized", skip_serializing_if = "Option::is_none")]
    pub jp_name_normalized: Option<String>,
    #[serde(rename = "link_name")]
    pub link_name: String,
    #[serde(rename = "link_name_normalized")]
    pub link_name_normalized: String,
    #[serde(rename = "card_type")]
    pub card_type: models::CardType,
    #[serde(rename = "main_color")]
    pub main_color: String,
    #[serde(rename = "side_color", skip_serializing_if = "Option::is_none")]
    pub side_color: Option<String>,
    #[serde(rename = "wiki_template", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub wiki_template: Option<Option<serde_json::Value>>,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl Card {
    pub fn new(card_id: String, char_id: String, rarity: String, name: String, name_normalized: String, link_name: String, link_name_normalized: String, card_type: models::CardType, main_color: String, updated_at: String) -> Card {
        Card {
            card_id,
            char_id,
            rarity,
            rarity_modifier: None,
            name,
            name_normalized,
            jp_name: None,
            jp_name_normalized: None,
            link_name,
            link_name_normalized,
            card_type,
            main_color,
            side_color: None,
            wiki_template: None,
            updated_at,
        }
    }
}

