/*
 * PPQ API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CardIconUrls {
    #[serde(rename = "normal", skip_serializing_if = "Option::is_none")]
    pub normal: Option<String>,
    #[serde(rename = "dual_shift", skip_serializing_if = "Option::is_none")]
    pub dual_shift: Option<String>,
    #[serde(rename = "extra_power", skip_serializing_if = "Option::is_none")]
    pub extra_power: Option<String>,
    #[serde(rename = "extra_power_dual_shift", skip_serializing_if = "Option::is_none")]
    pub extra_power_dual_shift: Option<String>,
}

impl CardIconUrls {
    pub fn new() -> CardIconUrls {
        CardIconUrls {
            normal: None,
            dual_shift: None,
            extra_power: None,
            extra_power_dual_shift: None,
        }
    }
}

