/*
 * PPQ API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CardType {
    #[serde(rename = "character")]
    Character,
    #[serde(rename = "material")]
    Material,

}

impl std::fmt::Display for CardType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Character => write!(f, "character"),
            Self::Material => write!(f, "material"),
        }
    }
}

impl Default for CardType {
    fn default() -> CardType {
        Self::Character
    }
}

