/*
 * PPQ API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CardFullArtUrls {
    #[serde(rename = "normal_left", skip_serializing_if = "Option::is_none")]
    pub normal_left: Option<String>,
    #[serde(rename = "normal_right", skip_serializing_if = "Option::is_none")]
    pub normal_right: Option<String>,
    #[serde(rename = "extra_power_left", skip_serializing_if = "Option::is_none")]
    pub extra_power_left: Option<String>,
    #[serde(rename = "extra_power_right", skip_serializing_if = "Option::is_none")]
    pub extra_power_right: Option<String>,
    /// Full Power or Cross Ability
    #[serde(rename = "ss", skip_serializing_if = "Option::is_none")]
    pub ss: Option<String>,
    #[serde(rename = "extra_power_ss", skip_serializing_if = "Option::is_none")]
    pub extra_power_ss: Option<String>,
    #[serde(rename = "dual_shift_left", skip_serializing_if = "Option::is_none")]
    pub dual_shift_left: Option<String>,
    #[serde(rename = "dual_shift_right", skip_serializing_if = "Option::is_none")]
    pub dual_shift_right: Option<String>,
    #[serde(rename = "extra_power_dual_shift", skip_serializing_if = "Option::is_none")]
    pub extra_power_dual_shift: Option<String>,
}

impl CardFullArtUrls {
    pub fn new() -> CardFullArtUrls {
        CardFullArtUrls {
            normal_left: None,
            normal_right: None,
            extra_power_left: None,
            extra_power_right: None,
            ss: None,
            extra_power_ss: None,
            dual_shift_left: None,
            dual_shift_right: None,
            extra_power_dual_shift: None,
        }
    }
}

