/*
 * PPQ API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Character {
    #[serde(rename = "char_id")]
    pub char_id: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "jp_name", skip_serializing_if = "Option::is_none")]
    pub jp_name: Option<String>,
    #[serde(rename = "link_name", skip_serializing_if = "Option::is_none")]
    pub link_name: Option<String>,
    #[serde(rename = "main_color", skip_serializing_if = "Option::is_none")]
    pub main_color: Option<String>,
    #[serde(rename = "side_color", skip_serializing_if = "Option::is_none")]
    pub side_color: Option<String>,
    #[serde(rename = "type1", skip_serializing_if = "Option::is_none")]
    pub type1: Option<String>,
    #[serde(rename = "type2", skip_serializing_if = "Option::is_none")]
    pub type2: Option<String>,
    #[serde(rename = "voice_trans", skip_serializing_if = "Option::is_none")]
    pub voice_trans: Option<String>,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl Character {
    pub fn new(char_id: String, updated_at: String) -> Character {
        Character {
            char_id,
            name: None,
            jp_name: None,
            link_name: None,
            main_color: None,
            side_color: None,
            type1: None,
            type2: None,
            voice_trans: None,
            updated_at,
        }
    }
}

