/*
 * PPQ API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteCount {
    #[serde(rename = "count")]
    pub count: i32,
}

impl DeleteCount {
    pub fn new(count: i32) -> DeleteCount {
        DeleteCount {
            count,
        }
    }
}

