/*
 * PPQ API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventType {
    #[serde(rename = "guild_rush")]
    GuildRush,
    #[serde(rename = "limited_story")]
    LimitedStory,
    #[serde(rename = "bingo_arena")]
    BingoArena,
    #[serde(rename = "collection")]
    Collection,
    #[serde(rename = "tournament")]
    Tournament,
    #[serde(rename = "story_quest")]
    StoryQuest,
    #[serde(rename = "intrusion")]
    Intrusion,
    #[serde(rename = "hunting")]
    Hunting,
    #[serde(rename = "treasure")]
    Treasure,
    #[serde(rename = "unknown")]
    Unknown,

}

impl std::fmt::Display for EventType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::GuildRush => write!(f, "guild_rush"),
            Self::LimitedStory => write!(f, "limited_story"),
            Self::BingoArena => write!(f, "bingo_arena"),
            Self::Collection => write!(f, "collection"),
            Self::Tournament => write!(f, "tournament"),
            Self::StoryQuest => write!(f, "story_quest"),
            Self::Intrusion => write!(f, "intrusion"),
            Self::Hunting => write!(f, "hunting"),
            Self::Treasure => write!(f, "treasure"),
            Self::Unknown => write!(f, "unknown"),
        }
    }
}

impl Default for EventType {
    fn default() -> EventType {
        Self::GuildRush
    }
}

