/*
 * PPQ API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Lore {
    #[serde(rename = "card_id")]
    pub card_id: String,
    #[serde(rename = "flavor_text_jp", skip_serializing_if = "Option::is_none")]
    pub flavor_text_jp: Option<String>,
    #[serde(rename = "flavor_text_en", skip_serializing_if = "Option::is_none")]
    pub flavor_text_en: Option<String>,
    #[serde(rename = "monologue_lines")]
    pub monologue_lines: Vec<models::MonologueLine>,
    #[serde(rename = "translator", skip_serializing_if = "Option::is_none")]
    pub translator: Option<String>,
    #[serde(rename = "editor", skip_serializing_if = "Option::is_none")]
    pub editor: Option<String>,
}

impl Lore {
    pub fn new(card_id: String, monologue_lines: Vec<models::MonologueLine>) -> Lore {
        Lore {
            card_id,
            flavor_text_jp: None,
            flavor_text_en: None,
            monologue_lines,
            translator: None,
            editor: None,
        }
    }
}

