/*
 * PPQ API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonologueLine {
    #[serde(rename = "jp", skip_serializing_if = "Option::is_none")]
    pub jp: Option<String>,
    #[serde(rename = "en", skip_serializing_if = "Option::is_none")]
    pub en: Option<String>,
}

impl MonologueLine {
    pub fn new() -> MonologueLine {
        MonologueLine {
            jp: None,
            en: None,
        }
    }
}

