/*
 * PPQ API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotFoundReason {
    #[serde(rename = "not_found")]
    pub not_found: models::NotFoundReasonEnum,
}

impl NotFoundReason {
    pub fn new(not_found: models::NotFoundReasonEnum) -> NotFoundReason {
        NotFoundReason {
            not_found,
        }
    }
}

