/*
 * PPQ API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NotFoundReasonEnum {
    #[serde(rename = "alias")]
    Alias,
    #[serde(rename = "rarity")]
    Rarity,

}

impl std::fmt::Display for NotFoundReasonEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Alias => write!(f, "alias"),
            Self::Rarity => write!(f, "rarity"),
        }
    }
}

impl Default for NotFoundReasonEnum {
    fn default() -> NotFoundReasonEnum {
        Self::Alias
    }
}

