/*
 * PPQ API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PpqEvent {
    #[serde(rename = "icon_url", skip_serializing_if = "Option::is_none")]
    pub icon_url: Option<String>,
    #[serde(rename = "event_type")]
    pub event_type: models::EventType,
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<String>,
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<String>,
    #[serde(rename = "remaining_seconds", skip_serializing_if = "Option::is_none")]
    pub remaining_seconds: Option<i64>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "link", skip_serializing_if = "Option::is_none")]
    pub link: Option<String>,
    #[serde(rename = "jp_name", skip_serializing_if = "Option::is_none")]
    pub jp_name: Option<String>,
}

impl PpqEvent {
    pub fn new(event_type: models::EventType) -> PpqEvent {
        PpqEvent {
            icon_url: None,
            event_type,
            start: None,
            end: None,
            remaining_seconds: None,
            name: None,
            link: None,
            jp_name: None,
        }
    }
}

