/*
 * PPQ API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PpqEventSchedule {
    #[serde(rename = "fetched_at")]
    pub fetched_at: String,
    #[serde(rename = "upcoming")]
    pub upcoming: Vec<models::PpqEvent>,
    #[serde(rename = "ongoing")]
    pub ongoing: Vec<models::PpqEvent>,
    #[serde(rename = "other")]
    pub other: Vec<models::PpqEvent>,
}

impl PpqEventSchedule {
    pub fn new(fetched_at: String, upcoming: Vec<models::PpqEvent>, ongoing: Vec<models::PpqEvent>, other: Vec<models::PpqEvent>) -> PpqEventSchedule {
        PpqEventSchedule {
            fetched_at,
            upcoming,
            ongoing,
            other,
        }
    }
}

