/**
 * PPQ API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CardIconUrls {
    'normal'?: string;
    'dualShift'?: string;
    'extraPower'?: string;
    'extraPowerDualShift'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "normal",
            "baseName": "normal",
            "type": "string",
            "format": ""
        },
        {
            "name": "dualShift",
            "baseName": "dual_shift",
            "type": "string",
            "format": ""
        },
        {
            "name": "extraPower",
            "baseName": "extra_power",
            "type": "string",
            "format": ""
        },
        {
            "name": "extraPowerDualShift",
            "baseName": "extra_power_dual_shift",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CardIconUrls.attributeTypeMap;
    }

    public constructor() {
    }
}
