/**
 * PPQ API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CardTemplateData {
    'name': string;
    'rarity': string;
    'code': string;
    'link'?: string;
    'jpname'?: string;
    'color'?: string;
    'color2'?: string;
    'type1'?: string;
    'type2'?: string;
    'maxlv'?: string;
    'cost'?: string;
    'hpmax'?: string;
    'atkmax'?: string;
    'rcvmax'?: string;
    'backast'?: string;
    'backlst'?: string;
    'ast'?: string;
    'astn'?: string;
    'aste'?: string;
    'ast2'?: string;
    'ast2n'?: string;
    'ast2e'?: string;
    'ast3'?: string;
    'ast3n'?: string;
    'ast3e'?: string;
    'jpast'?: string;
    'jpast2'?: string;
    'jpast3'?: string;
    'lst'?: string;
    'lste'?: string;
    'lst2'?: string;
    'lst2e'?: string;
    'lst3'?: string;
    'lst3e'?: string;
    'lst3t'?: string;
    'jplst'?: string;
    'jplst2'?: string;
    'jplst3'?: string;
    'as'?: string;
    'jpas'?: string;
    'asn'?: string;
    'asfn'?: string;
    'aslv'?: string;
    'ase'?: string;
    'asfe'?: string;
    'ls'?: string;
    'lslv'?: string;
    'lse'?: string;
    'jpls'?: string;
    'bs'?: string;
    'jpbs'?: string;
    'bslv'?: string;
    'bsn'?: string;
    'bse'?: string;
    'ca'?: string;
    'jpca'?: string;
    'calv'?: string;
    'can'?: string;
    'cae'?: string;
    'caalt'?: string;
    'ts'?: string;
    'tstype'?: string;
    'tsact'?: string;
    'tse'?: string;
    'tse2'?: string;
    'tse3'?: string;
    'tse4'?: string;
    'combin1'?: string;
    'combin2'?: string;
    'combin3'?: string;
    'combin4'?: string;
    'combin5'?: string;
    'combin6'?: string;
    'ss'?: string;
    'jpss'?: string;
    'sslv'?: string;
    'ssstart'?: string;
    'ssend'?: string;
    'sse'?: string;
    /**
    * Dual Shift Activation Count
    */
    'dsn'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "rarity",
            "baseName": "rarity",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string",
            "format": ""
        },
        {
            "name": "jpname",
            "baseName": "jpname",
            "type": "string",
            "format": ""
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string",
            "format": ""
        },
        {
            "name": "color2",
            "baseName": "color2",
            "type": "string",
            "format": ""
        },
        {
            "name": "type1",
            "baseName": "type1",
            "type": "string",
            "format": ""
        },
        {
            "name": "type2",
            "baseName": "type2",
            "type": "string",
            "format": ""
        },
        {
            "name": "maxlv",
            "baseName": "maxlv",
            "type": "string",
            "format": ""
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "string",
            "format": ""
        },
        {
            "name": "hpmax",
            "baseName": "hpmax",
            "type": "string",
            "format": ""
        },
        {
            "name": "atkmax",
            "baseName": "atkmax",
            "type": "string",
            "format": ""
        },
        {
            "name": "rcvmax",
            "baseName": "rcvmax",
            "type": "string",
            "format": ""
        },
        {
            "name": "backast",
            "baseName": "backast",
            "type": "string",
            "format": ""
        },
        {
            "name": "backlst",
            "baseName": "backlst",
            "type": "string",
            "format": ""
        },
        {
            "name": "ast",
            "baseName": "ast",
            "type": "string",
            "format": ""
        },
        {
            "name": "astn",
            "baseName": "astn",
            "type": "string",
            "format": ""
        },
        {
            "name": "aste",
            "baseName": "aste",
            "type": "string",
            "format": ""
        },
        {
            "name": "ast2",
            "baseName": "ast2",
            "type": "string",
            "format": ""
        },
        {
            "name": "ast2n",
            "baseName": "ast2n",
            "type": "string",
            "format": ""
        },
        {
            "name": "ast2e",
            "baseName": "ast2e",
            "type": "string",
            "format": ""
        },
        {
            "name": "ast3",
            "baseName": "ast3",
            "type": "string",
            "format": ""
        },
        {
            "name": "ast3n",
            "baseName": "ast3n",
            "type": "string",
            "format": ""
        },
        {
            "name": "ast3e",
            "baseName": "ast3e",
            "type": "string",
            "format": ""
        },
        {
            "name": "jpast",
            "baseName": "jpast",
            "type": "string",
            "format": ""
        },
        {
            "name": "jpast2",
            "baseName": "jpast2",
            "type": "string",
            "format": ""
        },
        {
            "name": "jpast3",
            "baseName": "jpast3",
            "type": "string",
            "format": ""
        },
        {
            "name": "lst",
            "baseName": "lst",
            "type": "string",
            "format": ""
        },
        {
            "name": "lste",
            "baseName": "lste",
            "type": "string",
            "format": ""
        },
        {
            "name": "lst2",
            "baseName": "lst2",
            "type": "string",
            "format": ""
        },
        {
            "name": "lst2e",
            "baseName": "lst2e",
            "type": "string",
            "format": ""
        },
        {
            "name": "lst3",
            "baseName": "lst3",
            "type": "string",
            "format": ""
        },
        {
            "name": "lst3e",
            "baseName": "lst3e",
            "type": "string",
            "format": ""
        },
        {
            "name": "lst3t",
            "baseName": "lst3t",
            "type": "string",
            "format": ""
        },
        {
            "name": "jplst",
            "baseName": "jplst",
            "type": "string",
            "format": ""
        },
        {
            "name": "jplst2",
            "baseName": "jplst2",
            "type": "string",
            "format": ""
        },
        {
            "name": "jplst3",
            "baseName": "jplst3",
            "type": "string",
            "format": ""
        },
        {
            "name": "as",
            "baseName": "as",
            "type": "string",
            "format": ""
        },
        {
            "name": "jpas",
            "baseName": "jpas",
            "type": "string",
            "format": ""
        },
        {
            "name": "asn",
            "baseName": "asn",
            "type": "string",
            "format": ""
        },
        {
            "name": "asfn",
            "baseName": "asfn",
            "type": "string",
            "format": ""
        },
        {
            "name": "aslv",
            "baseName": "aslv",
            "type": "string",
            "format": ""
        },
        {
            "name": "ase",
            "baseName": "ase",
            "type": "string",
            "format": ""
        },
        {
            "name": "asfe",
            "baseName": "asfe",
            "type": "string",
            "format": ""
        },
        {
            "name": "ls",
            "baseName": "ls",
            "type": "string",
            "format": ""
        },
        {
            "name": "lslv",
            "baseName": "lslv",
            "type": "string",
            "format": ""
        },
        {
            "name": "lse",
            "baseName": "lse",
            "type": "string",
            "format": ""
        },
        {
            "name": "jpls",
            "baseName": "jpls",
            "type": "string",
            "format": ""
        },
        {
            "name": "bs",
            "baseName": "bs",
            "type": "string",
            "format": ""
        },
        {
            "name": "jpbs",
            "baseName": "jpbs",
            "type": "string",
            "format": ""
        },
        {
            "name": "bslv",
            "baseName": "bslv",
            "type": "string",
            "format": ""
        },
        {
            "name": "bsn",
            "baseName": "bsn",
            "type": "string",
            "format": ""
        },
        {
            "name": "bse",
            "baseName": "bse",
            "type": "string",
            "format": ""
        },
        {
            "name": "ca",
            "baseName": "ca",
            "type": "string",
            "format": ""
        },
        {
            "name": "jpca",
            "baseName": "jpca",
            "type": "string",
            "format": ""
        },
        {
            "name": "calv",
            "baseName": "calv",
            "type": "string",
            "format": ""
        },
        {
            "name": "can",
            "baseName": "can",
            "type": "string",
            "format": ""
        },
        {
            "name": "cae",
            "baseName": "cae",
            "type": "string",
            "format": ""
        },
        {
            "name": "caalt",
            "baseName": "caalt",
            "type": "string",
            "format": ""
        },
        {
            "name": "ts",
            "baseName": "ts",
            "type": "string",
            "format": ""
        },
        {
            "name": "tstype",
            "baseName": "tstype",
            "type": "string",
            "format": ""
        },
        {
            "name": "tsact",
            "baseName": "tsact",
            "type": "string",
            "format": ""
        },
        {
            "name": "tse",
            "baseName": "tse",
            "type": "string",
            "format": ""
        },
        {
            "name": "tse2",
            "baseName": "tse2",
            "type": "string",
            "format": ""
        },
        {
            "name": "tse3",
            "baseName": "tse3",
            "type": "string",
            "format": ""
        },
        {
            "name": "tse4",
            "baseName": "tse4",
            "type": "string",
            "format": ""
        },
        {
            "name": "combin1",
            "baseName": "combin1",
            "type": "string",
            "format": ""
        },
        {
            "name": "combin2",
            "baseName": "combin2",
            "type": "string",
            "format": ""
        },
        {
            "name": "combin3",
            "baseName": "combin3",
            "type": "string",
            "format": ""
        },
        {
            "name": "combin4",
            "baseName": "combin4",
            "type": "string",
            "format": ""
        },
        {
            "name": "combin5",
            "baseName": "combin5",
            "type": "string",
            "format": ""
        },
        {
            "name": "combin6",
            "baseName": "combin6",
            "type": "string",
            "format": ""
        },
        {
            "name": "ss",
            "baseName": "ss",
            "type": "string",
            "format": ""
        },
        {
            "name": "jpss",
            "baseName": "jpss",
            "type": "string",
            "format": ""
        },
        {
            "name": "sslv",
            "baseName": "sslv",
            "type": "string",
            "format": ""
        },
        {
            "name": "ssstart",
            "baseName": "ssstart",
            "type": "string",
            "format": ""
        },
        {
            "name": "ssend",
            "baseName": "ssend",
            "type": "string",
            "format": ""
        },
        {
            "name": "sse",
            "baseName": "sse",
            "type": "string",
            "format": ""
        },
        {
            "name": "dsn",
            "baseName": "dsn",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CardTemplateData.attributeTypeMap;
    }

    public constructor() {
    }
}
