/**
 * PPQ API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CardFullArtUrls {
    'normalLeft'?: string;
    'normalRight'?: string;
    'extraPowerLeft'?: string;
    'extraPowerRight'?: string;
    /**
    * Full Power or Cross Ability
    */
    'ss'?: string;
    'extraPowerSs'?: string;
    'dualShiftLeft'?: string;
    'dualShiftRight'?: string;
    'extraPowerDualShift'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "normalLeft",
            "baseName": "normal_left",
            "type": "string",
            "format": ""
        },
        {
            "name": "normalRight",
            "baseName": "normal_right",
            "type": "string",
            "format": ""
        },
        {
            "name": "extraPowerLeft",
            "baseName": "extra_power_left",
            "type": "string",
            "format": ""
        },
        {
            "name": "extraPowerRight",
            "baseName": "extra_power_right",
            "type": "string",
            "format": ""
        },
        {
            "name": "ss",
            "baseName": "ss",
            "type": "string",
            "format": ""
        },
        {
            "name": "extraPowerSs",
            "baseName": "extra_power_ss",
            "type": "string",
            "format": ""
        },
        {
            "name": "dualShiftLeft",
            "baseName": "dual_shift_left",
            "type": "string",
            "format": ""
        },
        {
            "name": "dualShiftRight",
            "baseName": "dual_shift_right",
            "type": "string",
            "format": ""
        },
        {
            "name": "extraPowerDualShift",
            "baseName": "extra_power_dual_shift",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CardFullArtUrls.attributeTypeMap;
    }

    public constructor() {
    }
}
