/**
 * PPQ API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CardType } from '../models/CardType';
import { HttpFile } from '../http/http';

export class CardCreate {
    'cardId': string;
    /**
    * Foreign key to the character table
    */
    'charId': string;
    'rarity': string;
    /**
    * 6-1, 6-2 (6S)
    */
    'rarityModifier'?: string;
    'name': string;
    /**
    * NFKD normalized with special characters removed
    */
    'nameNormalized': string;
    'jpName'?: string;
    'jpNameNormalized'?: string;
    'linkName': string;
    'linkNameNormalized': string;
    'cardType': CardType;
    'mainColor': string;
    'sideColor'?: string;
    'updatedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cardId",
            "baseName": "card_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "charId",
            "baseName": "char_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "rarity",
            "baseName": "rarity",
            "type": "string",
            "format": ""
        },
        {
            "name": "rarityModifier",
            "baseName": "rarity_modifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "nameNormalized",
            "baseName": "name_normalized",
            "type": "string",
            "format": ""
        },
        {
            "name": "jpName",
            "baseName": "jp_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "jpNameNormalized",
            "baseName": "jp_name_normalized",
            "type": "string",
            "format": ""
        },
        {
            "name": "linkName",
            "baseName": "link_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "linkNameNormalized",
            "baseName": "link_name_normalized",
            "type": "string",
            "format": ""
        },
        {
            "name": "cardType",
            "baseName": "card_type",
            "type": "CardType",
            "format": ""
        },
        {
            "name": "mainColor",
            "baseName": "main_color",
            "type": "string",
            "format": ""
        },
        {
            "name": "sideColor",
            "baseName": "side_color",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return CardCreate.attributeTypeMap;
    }

    public constructor() {
    }
}


