/**
 * PPQ API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CharacterCreate {
    'name'?: string;
    'jpName'?: string;
    'linkName'?: string;
    'mainColor'?: string;
    'sideColor'?: string;
    'type1'?: string;
    'type2'?: string;
    'voiceTrans'?: string;
    'updatedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "jpName",
            "baseName": "jp_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "linkName",
            "baseName": "link_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "mainColor",
            "baseName": "main_color",
            "type": "string",
            "format": ""
        },
        {
            "name": "sideColor",
            "baseName": "side_color",
            "type": "string",
            "format": ""
        },
        {
            "name": "type1",
            "baseName": "type1",
            "type": "string",
            "format": ""
        },
        {
            "name": "type2",
            "baseName": "type2",
            "type": "string",
            "format": ""
        },
        {
            "name": "voiceTrans",
            "baseName": "voice_trans",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return CharacterCreate.attributeTypeMap;
    }

    public constructor() {
    }
}
