/**
 * PPQ API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum EventType {
    GuildRush = 'guild_rush',
    LimitedStory = 'limited_story',
    BingoArena = 'bingo_arena',
    Collection = 'collection',
    Tournament = 'tournament',
    StoryQuest = 'story_quest',
    Intrusion = 'intrusion',
    Hunting = 'hunting',
    Treasure = 'treasure',
    Unknown = 'unknown'
}
