/**
 * PPQ API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MonologueLine } from '../models/MonologueLine';
import { HttpFile } from '../http/http';

export class Lore {
    'cardId': string;
    'flavorTextJp'?: string;
    'flavorTextEn'?: string;
    'monologueLines': Array<MonologueLine>;
    'translator'?: string;
    'editor'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cardId",
            "baseName": "card_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "flavorTextJp",
            "baseName": "flavor_text_jp",
            "type": "string",
            "format": ""
        },
        {
            "name": "flavorTextEn",
            "baseName": "flavor_text_en",
            "type": "string",
            "format": ""
        },
        {
            "name": "monologueLines",
            "baseName": "monologue_lines",
            "type": "Array<MonologueLine>",
            "format": ""
        },
        {
            "name": "translator",
            "baseName": "translator",
            "type": "string",
            "format": ""
        },
        {
            "name": "editor",
            "baseName": "editor",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Lore.attributeTypeMap;
    }

    public constructor() {
    }
}
