/**
 * PPQ API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NotFoundReasonEnum } from '../models/NotFoundReasonEnum';
import { HttpFile } from '../http/http';

export class NotFoundReason {
    'notFound': NotFoundReasonEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "notFound",
            "baseName": "not_found",
            "type": "NotFoundReasonEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NotFoundReason.attributeTypeMap;
    }

    public constructor() {
    }
}


