/**
 * PPQ API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EventType } from '../models/EventType';
import { HttpFile } from '../http/http';

export class PpqEvent {
    'iconUrl'?: string;
    'eventType': EventType;
    'start'?: Date;
    'end'?: Date;
    'remainingSeconds'?: number;
    'name'?: string;
    'link'?: string;
    'jpName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "iconUrl",
            "baseName": "icon_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "eventType",
            "baseName": "event_type",
            "type": "EventType",
            "format": ""
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "end",
            "baseName": "end",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "remainingSeconds",
            "baseName": "remaining_seconds",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string",
            "format": ""
        },
        {
            "name": "jpName",
            "baseName": "jp_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PpqEvent.attributeTypeMap;
    }

    public constructor() {
    }
}


