/**
 * PPQ API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PpqEvent } from '../models/PpqEvent';
import { HttpFile } from '../http/http';

export class PpqEventSchedule {
    'fetchedAt': Date;
    'upcoming': Array<PpqEvent>;
    'ongoing': Array<PpqEvent>;
    'other': Array<PpqEvent>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fetchedAt",
            "baseName": "fetched_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "upcoming",
            "baseName": "upcoming",
            "type": "Array<PpqEvent>",
            "format": ""
        },
        {
            "name": "ongoing",
            "baseName": "ongoing",
            "type": "Array<PpqEvent>",
            "format": ""
        },
        {
            "name": "other",
            "baseName": "other",
            "type": "Array<PpqEvent>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PpqEventSchedule.attributeTypeMap;
    }

    public constructor() {
    }
}
