use poem_openapi::Object;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Object, Serialize, Deserialize, PartialEq, Eq)]
pub struct CardTemplateData {
    pub name: String,
    pub rarity: String,
    pub code: String,
    pub link: Option<String>,
    pub jpname: Option<String>,
    pub color: Option<String>,
    pub color2: Option<String>,
    pub type1: Option<String>,
    pub type2: Option<String>,
    pub maxlv: Option<String>,
    pub cost: Option<String>,
    pub hpmax: Option<String>,
    pub atkmax: Option<String>,
    pub rcvmax: Option<String>,
    pub backast: Option<String>,
    pub backlst: Option<String>,
    pub ast: Option<String>,
    pub astn: Option<String>,
    pub aste: Option<String>,
    pub ast2: Option<String>,
    pub ast2n: Option<String>,
    pub ast2e: Option<String>,
    pub ast3: Option<String>,
    pub ast3n: Option<String>,
    pub ast3e: Option<String>,
    pub jpast: Option<String>,
    pub jpast2: Option<String>,
    pub jpast3: Option<String>,
    pub lst: Option<String>,
    pub lste: Option<String>,
    pub lst2: Option<String>,
    pub lst2e: Option<String>,
    pub lst3: Option<String>,
    pub lst3e: Option<String>,
    pub lst3t: Option<String>,
    pub jplst: Option<String>,
    pub jplst2: Option<String>,
    pub jplst3: Option<String>,
    pub r#as: Option<String>,
    pub jpas: Option<String>,
    pub asn: Option<String>,
    pub asfn: Option<String>,
    pub aslv: Option<String>,
    pub ase: Option<String>,
    pub asfe: Option<String>,
    pub ls: Option<String>,
    pub lslv: Option<String>,
    pub lse: Option<String>,
    pub jpls: Option<String>,
    pub bs: Option<String>,
    pub jpbs: Option<String>,
    pub bslv: Option<String>,
    pub bsn: Option<String>,
    pub bse: Option<String>,
    pub ca: Option<String>,
    pub jpca: Option<String>,
    pub calv: Option<String>,
    pub can: Option<String>,
    pub cae: Option<String>,
    pub caalt: Option<String>,
    pub ts: Option<String>,
    pub tstype: Option<String>,
    pub tsact: Option<String>,
    pub tse: Option<String>,
    pub tse2: Option<String>,
    pub tse3: Option<String>,
    pub tse4: Option<String>,
    // TODO: how many tse are there?
    pub combin1: Option<String>,
    pub combin2: Option<String>,
    pub combin3: Option<String>,
    pub combin4: Option<String>,
    pub combin5: Option<String>,
    pub combin6: Option<String>,
    pub ss: Option<String>,
    pub jpss: Option<String>,
    pub sslv: Option<String>,
    pub ssstart: Option<String>,
    pub ssend: Option<String>,
    pub sse: Option<String>,
}

impl Default for CardTemplateData {
    fn default() -> Self {
        Self {
            name: String::default(),
            rarity: String::default(),
            code: String::default(),
            link: None,
            jpname: None,
            color: None,
            color2: None,
            type1: None,
            type2: None,
            maxlv: None,
            cost: None,
            hpmax: None,
            atkmax: None,
            rcvmax: None,
            backast: None,
            backlst: None,
            ast: None,
            astn: None,
            aste: None,
            ast2: None,
            ast2n: None,
            ast2e: None,
            ast3: None,
            ast3n: None,
            ast3e: None,
            jpast: None,
            jpast2: None,
            jpast3: None,
            lst: None,
            lste: None,
            lst2: None,
            lst2e: None,
            lst3: None,
            lst3e: None,
            lst3t: None,
            jplst: None,
            jplst2: None,
            jplst3: None,
            r#as: None,
            jpas: None,
            asn: None,
            asfn: None,
            aslv: None,
            ase: None,
            asfe: None,
            ls: None,
            lslv: None,
            lse: None,
            jpls: None,
            bs: None,
            jpbs: None,
            bslv: None,
            bsn: None,
            bse: None,
            ca: None,
            jpca: None,
            calv: None,
            can: None,
            cae: None,
            caalt: None,
            ts: None,
            tstype: None,
            tsact: None,
            tse: None,
            tse2: None,
            tse3: None,
            tse4: None,
            combin1: None,
            combin2: None,
            combin3: None,
            combin4: None,
            combin5: None,
            combin6: None,
            ss: None,
            jpss: None,
            sslv: None,
            ssstart: None,
            ssend: None,
            sse: None,
        }
    }
}
