/*
 * Yotarou API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KagaData {
    #[serde(rename = "kaga_id")]
    pub kaga_id: String,
    #[serde(rename = "url")]
    pub url: String,
}

impl KagaData {
    pub fn new(kaga_id: String, url: String) -> KagaData {
        KagaData {
            kaga_id,
            url,
        }
    }
}

