/*
 * Yotarou API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LeaderboardChannel {
    #[serde(rename = "server_id")]
    pub server_id: String,
    #[serde(rename = "game_type")]
    pub game_type: String,
    #[serde(rename = "channel_id")]
    pub channel_id: String,
}

impl LeaderboardChannel {
    pub fn new(server_id: String, game_type: String, channel_id: String) -> LeaderboardChannel {
        LeaderboardChannel {
            server_id,
            game_type,
            channel_id,
        }
    }
}

