/*
 * Yotarou API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LeaderboardChannelCreate {
    #[serde(rename = "channel_id")]
    pub channel_id: String,
}

impl LeaderboardChannelCreate {
    pub fn new(channel_id: String) -> LeaderboardChannelCreate {
        LeaderboardChannelCreate {
            channel_id,
        }
    }
}

