/*
 * Yotarou API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerSettings {
    #[serde(rename = "server_id")]
    pub server_id: String,
}

impl ServerSettings {
    pub fn new(server_id: String) -> ServerSettings {
        ServerSettings {
            server_id,
        }
    }
}

