/*
 * Yotarou API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserRanking {
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "server_id")]
    pub server_id: String,
    #[serde(rename = "game_type")]
    pub game_type: String,
    #[serde(rename = "correct")]
    pub correct: i32,
    #[serde(rename = "ranking")]
    pub ranking: i64,
}

impl UserRanking {
    pub fn new(user_id: String, server_id: String, game_type: String, correct: i32, ranking: i64) -> UserRanking {
        UserRanking {
            user_id,
            server_id,
            game_type,
            correct,
            ranking,
        }
    }
}

